### ISSUE TITLE
Error in build when he generate the PTHash

### ISSUE THREAD

**Issue by coco875** [dtrifuno/quickphf#2]
he crash and make this error:
```
error[E0658]: use of unstable library feature 'int_log'
  --> /home/coco/.cargo/registry/src/github.com-1ecc6299db9ec823/quickphf_codegen-0.1.0/src/phf.rs:34:16
   |
34 |     let lg = n.ilog2() as f64;
   |                ^^^^^
   |
   = note: see issue #70887 <https://github.com/rust-lang/rust/issues/70887> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `quickphf_codegen` due to previous error
```

**Comment by coco875** [comment]
the rust version `rustc 1.66.1 (90743e729 2023-01-10) (built from a source tarball)`

**Comment by coco875** [comment]
ok ubuntu use a old version so he have this error by updating to the newest stable version it's work

**Comment by dtrifuno** [comment]
Yeah, it looks like `ilog2` was only added in 1.67. I just published a new version that should fix this, so you can either use a newer Rust version than 1.66, or use `quickphf_codegen` 0.1.1 which should work with the correct minimum Rust version of 1.56.
